version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "02:00"
      timezone: "Asia/Tokyo"
    groups:
      non-majors:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
